name: label_verify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  generic_shop_app_architecture:
    path: /Users/matanljubas/Projects/temp/generic_shop_app/plugins/arch
  generic_shop_app_content:
    path: /Users/matanljubas/Projects/temp/generic_shop_app/plugins/content
  image: ^4.5.3
  collection: ^1.19.0
  archive: ^4.0.2
  path_provider: ^2.1.5
  file_picker: ^8.1.7
  file_saver: ^0.2.14
  sqflite_common_ffi: ^2.3.4+4
  path: ^1.9.0
  printing: ^5.14.2
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.2
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/example/
    - assets/bin/
    - assets/img/
    - assets/svg/
