/// Model class representing document database format.
///
class LvModelDocumentCategory {
  /// Default, unnamed class constructor.
  ///
  LvModelDocumentCategory({
    required this.id,
    required this.label,
  });

  /// Document category identifier generated by the SQL database.
  ///
  final int id;

  /// Document category display label.
  ///
  final String label;

  /// Factory constructor used to generate a class instance from database data format.
  ///
  factory LvModelDocumentCategory.fromJson(Map<String, dynamic> json) {
    return LvModelDocumentCategory(
      id: json['id'],
      label: json['label'],
    );
  }

  /// Method used for generating data in the database format.
  ///
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'label': label,
    };
  }
}
